### ISSUE TITLE
When running the script, the following error occurs

### ISSUE THREAD

**Issue by mspythontu** [neo-chem-synth-wave/atom-to-atom-mapping#1]
The following error occurred: DGL backend not selected or invalid. Assuming PyTorch for now.
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable. Valid options are: pytorch, mxnet, tensorflow (all lowercase).

/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/torchdata/datapipes/__init__.py:18: UserWarning: 
################################################################################
WARNING!
The 'datapipes', 'dataloader2' modules are deprecated and will be removed in a
future torchdata release! Please see https://github.com/pytorch/data/issues/1196
to learn more and leave feedback.
################################################################################

deprecation_warning()
Traceback (most recent call last):
  File "scripts/map_reaction_smiles_using_indigo.py", line 8, in <module>
    from atom_to_atom_mapping.utility import IndigoAtomToAtomMappingUtility
  File "/home/top/atom-to-atom-mapping/atom_to_atom_mapping/utility/__init__.py", line 9, in <module>
    from atom_to_atom_mapping.utility.micc_snu.local_mapper import LocalMapperAtomToAtomMappingUtility
  File "/home/top/atom-to-atom-mapping/atom_to_atom_mapping/utility/micc_snu/__init__.py", line 3, in <module>
    from atom_to_atom_mapping.utility.micc_snu.local_mapper import LocalMapperAtomToAtomMappingUtility
  File "/home/top/atom-to-atom-mapping/atom_to_atom_mapping/utility/micc_snu/local_mapper.py", line 7, in <module>
    from localmapper import localmapper
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/localmapper/__init__.py", line 6, in <module>
    from .localmapper import localmapper
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/localmapper/localmapper.py", line 11, in <module>
    from .utils import *
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/localmapper/utils.py", line 3, in <module>
    import dgl
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 55, in <module>
    load_graphbolt()
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 45, in load_graphbolt
    raise FileNotFoundError(
FileNotFoundError: Cannot find DGL C++ graphbolt library at /home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/graphbolt/libgraphbolt_pytorch_2.4.1.so

**Comment by mspythontu** [comment]
And I downgraded PyTorch to version 2.2.0, and encountered the following error when running the command:
python scripts/map_reaction_smiles_using_indigo.py \
  --reaction_smiles "[O-][N+](=O)c1ccc(Br)cn1.CC(=O)Nc1ccc(O)cc1>>CC(=O)Nc1ccc(Oc2ccc(nc2)[N+]([O-])=O)cc1"
DGL backend not selected or invalid. Assuming PyTorch for now.
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable. Valid options are: pytorch, mxnet, tensorflow (all lowercase)
Traceback (most recent call last):
  File "scripts/map_reaction_smiles_using_indigo.py", line 8, in <module>
    from atom_to_atom_mapping.utility import IndigoAtomToAtomMappingUtility
  File "/home/top/atom-to-atom-mapping/atom_to_atom_mapping/utility/__init__.py", line 9, in <module>
    from atom_to_atom_mapping.utility.micc_snu.local_mapper import LocalMapperAtomToAtomMappingUtility
  File "/home/top/atom-to-atom-mapping/atom_to_atom_mapping/utility/micc_snu/__init__.py", line 3, in <module>
    from atom_to_atom_mapping.utility.micc_snu.local_mapper import LocalMapperAtomToAtomMappingUtility
  File "/home/top/atom-to-atom-mapping/atom_to_atom_mapping/utility/micc_snu/local_mapper.py", line 7, in <module>
    from localmapper import localmapper
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/localmapper/__init__.py", line 6, in <module>
    from .localmapper import localmapper
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/localmapper/localmapper.py", line 11, in <module>
    from .utils import *
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/localmapper/utils.py", line 3, in <module>
    import dgl
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 8, in <module>
    from .base import *
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/dgl/graphbolt/base.py", line 8, in <module>
    from torchdata.datapipes.iter import IterDataPipe
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/torchdata/datapipes/__init__.py", line 11, in <module>
    from . import iter, map, utils
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/torchdata/datapipes/iter/__init__.py", line 79, in <module>
    from torchdata.datapipes.iter.util.cacheholder import (
  File "/home/top/anaconda3/envs/atom-to-atom-mapping-env/lib/python3.8/site-packages/torchdata/datapipes/iter/util/cacheholder.py", line 24, in <module>
    from torch.utils._import_utils import dill_available
ModuleNotFoundError: No module named 'torch.utils._import_utils'

**Comment by hasic-haris** [comment]
Thank you for the interest in the repository. The error you are encountering has to do with the DGL library (it has trouble detecting the backend) which is required for the localmapper tool. As we are simply installing localmapper using pip, there is nothing to be done when it comes to this repository. I suggest going to the original repository (https://github.com/snu-micc/LocalMapper) and figuring out how to install DGL correctly on your local machine, and then simply adjusting the versions accordingly for this environment as well. Hope this helps.

**Comment by hasic-haris** [comment]
@mspythontu I've re-structured the pacakge and scripts a bit in the latest release so that only the approach being used is actually imported, and you won't have to deal with issues caused by LocalMapper when using Indigo, as in your case. Also, I've found that simply re-installing DGL works for me:

```
# Re-install the DGL library for PyTorch and CUDA library versions 2.4 and 12.1, respectively.
pip uninstall dgl
pip install dgl -f https://data.dgl.ai/wheels/torch-2.4/cu121/repo.html
```

Therefore, if you want to use LocalMapper, you can check the cuda and torch versions, and install the appropriate DGL version as well. Please let me know if you run into other issues as well. Hope this helps, and thanks for the interest in the repo.
